name: music-box

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"
  push:
    branches: master

jobs:
  musicbox:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install
        run: npm install

      - name: Update
        uses: ./
        env:
          LASTFM_KEY: ${{ secrets.LASTFM_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          LFMUSERNAME: ${{ secrets.LFMUSERNAME }}
          GIST_ID: ${{ secrets.GIST_ID }}
